- hosts: hieudeptrai
  remote_user: hieudeptrai
  become: yes
  become_method: sudo

  vars:
    - user: "hieudeptrai"

  tasks:
    # Install Gnome Tweak Tool
    - name: Install Gnome Tweak Tool
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - gnome-tweak-tool
        - bleachbit
        - ettercap-graphical
        - ibus-unikey
    
    - name: Restart ibus
      command: ibus restart
      ignore_errors: yes
    
    # Install theme
    - name: Install theme
      unarchive:
        src: ./.themes.zip
        dest: /home/{{user}}
    - name: Install icon
      unarchive:
        src: ./.icons.zip
        dest: /home/{{user}}
    
    # Install docker
    - name: Add docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: set up the repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        state: present

    - name: Install docker
      apt:
        name: "{{item}}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - docker-ce
        - docker-compose

    - name: add group docker
      user:
        name: "{{user}}"
        groups: docker
        append: yes
    
    # Install oh-my-zsh
    - name: Install zsh
      apt:
        name: "zsh"
        state: present

    - name: Set zsh is default
      user:
        name: "{{user}}"
        shell: /usr/bin/zsh

    - name: Download oh-my-zsh install script
      get_url:
        url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest: "/home/{{user}}/install.sh"
        mode: 0755

    - name: Install oh-my-zsh
      command: sh /home/{{user}}/install.sh
      become: yes
      become_user: "{{user}}"

    - name: delete script file
      file:
        path: "/home/{{user}}/install.sh"
        state: absent
    
    # Install VSCode
    - name: Add Microsoft GPG key
      apt_key:
        url: "https://packages.microsoft.com/keys/microsoft.asc"
        state: present

    - name: Add VSCode repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        filename: vscode
        state: present

    - name: Install vscode
      apt:
        name: code
        state: present

    # Install Golang
    - name: Add Go repository
      apt_repository:
        repo: ppa:longsleep/golang-backports

    - name: Install golang
      apt:
        name: golang-go
        state: present

    # Install Google Chrome
    - name: Add Google GPG key
      apt_key:
        url: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
        state: present
    
    - name: Add Google Chrome repository
      apt_repository:
        repo: deb http://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome
        state: present
      ignore_errors: yes

    - name: Install Google Chrome
      apt:
        name: google-chrome-stable
        state: present
    
    # Install Node.js
    - name: Install n
      get_url:
        url: https://raw.githubusercontent.com/tj/n/master/bin/n
        dest: "/usr/local/bin/n"
        mode: 0755
    - name: Install Node.js
      command: n stable